from rich import box    

# Min and Max scales for the thermometer widget
SCALE_MAX_TEMP = 35
SCALE_MIN_TEMP = 15




# Boarders
PRIMARY_BORDER_COLOUR = "#00D9FF"
PRIMARY_HIGHLIGHT_BORDER_STYLE = "#CEA500"
PRIMARY_BOX_STYLE = box.SQUARE

# Fonts
PRIMARY_FONT_STYLE = "#00D9FF"
PRIMARY_HIGHLIGHT_FONT_STYLE = "#FF0000"
SECONDARY_HIGHLIGHT_FONT_STYLE = 'bright_yellow'
SUBTLE_HIGHLIGHT_FONT_STYLE = "#0098B3"